// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx-TwUgO0NMYsKvl5SMiYVx9vBPLFk4sE',
    appId: '1:619576085482:web:a6acc414bf54a950ca8093',
    messagingSenderId: '619576085482',
    projectId: 'mynotes-flupro',
    authDomain: 'mynotes-flupro.firebaseapp.com',
    storageBucket: 'mynotes-flupro.appspot.com',
    measurementId: 'G-5Z8ZS0T616',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycuPZ_1baRzUlT2-BiPMnuUPXQDc_Vp4',
    appId: '1:619576085482:android:054088488dd221bbca8093',
    messagingSenderId: '619576085482',
    projectId: 'mynotes-flupro',
    storageBucket: 'mynotes-flupro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQUKUQsMQPYV8BVh1uyTjZKkKYYXgXfc8',
    appId: '1:619576085482:ios:63faa9ae4b02a48cca8093',
    messagingSenderId: '619576085482',
    projectId: 'mynotes-flupro',
    storageBucket: 'mynotes-flupro.appspot.com',
    iosClientId: '619576085482-4r5so5681j9gi1na1igb5ivmg9i4hdja.apps.googleusercontent.com',
    iosBundleId: 'com.app.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQUKUQsMQPYV8BVh1uyTjZKkKYYXgXfc8',
    appId: '1:619576085482:ios:63faa9ae4b02a48cca8093',
    messagingSenderId: '619576085482',
    projectId: 'mynotes-flupro',
    storageBucket: 'mynotes-flupro.appspot.com',
    iosClientId: '619576085482-4r5so5681j9gi1na1igb5ivmg9i4hdja.apps.googleusercontent.com',
    iosBundleId: 'com.app.mynotes',
  );
}
